export const acessTokenMock =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6IkFuZGVyc29uIiwiZW1haWwiOiJsZW9zaWx2YWNzYXN0QGdtYWlsLmNvbSIsImlhdCI6MTcwMDA0NDUwMywiZXhwIjoxNzAwNjQ5MzAzLCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiMyJ9.2nYeOIuvlJdQ29t_HDhd_paHGgKBJDszhAywtpl2tw8';
